[2023-12-09T01:00:28.581+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: parallel_dag.transform scheduled__2023-12-08T00:00:00+00:00 [queued]>
[2023-12-09T01:00:28.587+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: parallel_dag.transform scheduled__2023-12-08T00:00:00+00:00 [queued]>
[2023-12-09T01:00:28.587+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-12-09T01:00:28.587+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-12-09T01:00:28.587+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-12-09T01:00:28.594+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): transform> on 2023-12-08 00:00:00+00:00
[2023-12-09T01:00:28.600+0000] {standard_task_runner.py:55} INFO - Started process 46609 to run task
[2023-12-09T01:00:28.603+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'parallel_dag', 'transform', 'scheduled__2023-12-08T00:00:00+00:00', '--job-id', '265', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmp_4s5urr3']
[2023-12-09T01:00:28.603+0000] {standard_task_runner.py:83} INFO - Job 265: Subtask transform
[2023-12-09T01:00:28.642+0000] {task_command.py:388} INFO - Running <TaskInstance: parallel_dag.transform scheduled__2023-12-08T00:00:00+00:00 [running]> on host 4b7d8c96b1d6
[2023-12-09T01:00:28.677+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=transform
AIRFLOW_CTX_EXECUTION_DATE=2023-12-08T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-12-08T00:00:00+00:00
[2023-12-09T01:00:28.678+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-12-09T01:00:28.678+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'sleep 30']
[2023-12-09T01:00:28.687+0000] {subprocess.py:86} INFO - Output:
[2023-12-09T02:21:13.335+0000] {local_task_job.py:273} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2023-12-09T02:21:13.342+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 46609. PIDs of all processes in the group: [46610, 46609]
[2023-12-09T02:21:13.343+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 46609
[2023-12-09T02:21:13.346+0000] {taskinstance.py:1479} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-12-09T02:21:13.350+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2023-12-09T02:21:13.437+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=46610, status='terminated', started='01:00:28') (46610) terminated with exit code None
[2023-12-09T02:21:13.438+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=46609, status='terminated', exitcode=0, started='01:00:28') (46609) terminated with exit code 0
