[2023-11-04T00:02:58.882+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: user_processing.store_user scheduled__2023-11-03T00:00:00+00:00 [queued]>
[2023-11-04T00:02:58.886+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: user_processing.store_user scheduled__2023-11-03T00:00:00+00:00 [queued]>
[2023-11-04T00:02:58.886+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-11-04T00:02:58.886+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-11-04T00:02:58.886+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-11-04T00:02:58.893+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): store_user> on 2023-11-03 00:00:00+00:00
[2023-11-04T00:02:58.897+0000] {standard_task_runner.py:55} INFO - Started process 82345 to run task
[2023-11-04T00:02:58.899+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'store_user', 'scheduled__2023-11-03T00:00:00+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp43igajfx']
[2023-11-04T00:02:58.900+0000] {standard_task_runner.py:83} INFO - Job 43: Subtask store_user
[2023-11-04T00:02:58.930+0000] {task_command.py:388} INFO - Running <TaskInstance: user_processing.store_user scheduled__2023-11-03T00:00:00+00:00 [running]> on host cff42873677f
[2023-11-04T00:02:58.959+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=store_user
AIRFLOW_CTX_EXECUTION_DATE=2023-11-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-11-03T00:00:00+00:00
[2023-11-04T00:02:58.960+0000] {postgres.py:158} INFO - Running copy expert: COPY users FROM stdin WITH DELIMITER as ',', filename: /tmp/processed_user.csv
[2023-11-04T00:02:58.964+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2023-11-04T00:02:58.966+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-11-04T00:02:58.970+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=store_user, execution_date=20231103T000000, start_date=20231104T000258, end_date=20231104T000258
[2023-11-04T00:02:59.003+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-11-04T00:02:59.013+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
